//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace our.ui {
	
	
	public partial class AddTask {
		
		protected System.Web.UI.HtmlControls.HtmlButton Button1;
		
		protected System.Web.UI.HtmlControls.HtmlButton Button2;
		
		protected System.Web.UI.WebControls.Label Label5;
		
		protected System.Web.UI.WebControls.Label Label1;
		
		protected System.Web.UI.HtmlControls.HtmlButton Button4;
		
		protected System.Web.UI.WebControls.Label Label2;
		
		protected System.Web.UI.WebControls.Label Label3;
		
		protected System.Web.UI.HtmlControls.HtmlButton Button5;
		
		protected System.Web.UI.HtmlControls.HtmlButton Button6;
	}
}
